const ELEVATOR_STATES = {
  IDLE: 'idle',
  MOVING_UP: 'moving_up',
  MOVING_DOWN: 'moving_down',
  LOADING: 'loading',
  MAINTENANCE: 'maintenance'
}

const DIRECTIONS = {
  UP: 'up',
  DOWN: 'down',
  IDLE: 'idle'
}

const DEFAULT_CONFIG = {
  NUM_ELEVATORS: 3,
  NUM_FLOORS: 15,
  ELEVATOR_CAPACITY: 8,
  FLOOR_TRAVEL_TIME: 2000,
  DOOR_OPEN_TIME: 3000,
  SIMULATION_INTERVAL: 100
}

const PRIORITY_WEIGHTS = {
  STARVATION_THRESHOLD: 30000,
  CRITICAL_THRESHOLD: 60000,
  EXPONENTIAL_BASE: 1.8,
  MORNING_RUSH_MULTIPLIER: 2.0,
  EVENING_RUSH_MULTIPLIER: 1.5
}

module.exports = {
  ELEVATOR_STATES,
  DIRECTIONS,
  DEFAULT_CONFIG,
  PRIORITY_WEIGHTS
}